### ISSUE TITLE
Provide deployment instructions for deploying to prod kubernetes

### ISSUE THREAD

**Issue by iMartyn** [k8guard/k8guard-start-from-here#26] opened 2017-07-26 16:01 UTC
Currently the makefile (which makes _many_ assumptions) provides "magic" deployment to minikube or docker-engine.

There's no documentation on where to find yaml files to deploy to *actual* kubernetes clusters.

**Comment by medyagh** [comment] 2017-07-26 17:28
Hi there @iMartyn we currently deploy almost the exact same Yaml file in minikube to kuberentes. which part of it do you think is magic ?

The make file has steps for Building the go binaries and then Build docker files, and then publishing the dockerfiles to minikube's docker and then applying the yamls files to kuberentes.

you can replace the build process to your build process and publish the docker images to your favorite container registery. 

currently I am waiting on Docker hub to support multi stage docker builds https://github.com/docker/hub-feedback/issues/1039  then you could just use docker hub images instead of building them.

each microservice's deployment yaml is in minikube folder in this repo. (start-from-here repo) 
action, report, discover-cronjob, discover-api
and there is a folder called "core" for cassandra and kafka and memcached,

which if you have a cassandra or kafka as service somewhere (hopefully) , you can use that instead of deploying your own cassandra, kafka. however for minikube we deployed cassandra and kafka too so the user can try the whole thing out without have to worry about it.

**Comment by milsonian** [comment] 2017-07-26 17:39
I think the only tweak would be on the service.yml, which may not be a NodePort in most production environments, rather ClusterIP (with an ingress) or LoadBalancer (in e.g. GKE) - and you might add an ingress resource depending on your environment.  

It varies but some note to that effect or samples might be worthwhile.

**Comment by milsonian** [comment] 2017-07-26 17:41
..a local Helm chart could be a good way to express this when we get to it, btw.

**Comment by iMartyn** [comment] 2017-07-26 17:44
But where are the yaml files? Sure if you have minikube you can deploy with
`make build-deploy-minikube` and then try and get the yaml out but imagine
someone who has a running kubernetes cluster who doesn't want to install
minikube. Where in the docs does it tell you where the yaml to deploy is?

**Comment by medyagh** [comment] 2017-07-26 17:47
@iMartyn 
here are exact paths:

https://github.com/k8guard/k8guard-start-from-here/tree/master/minikube/action
https://github.com/k8guard/k8guard-start-from-here/tree/master/minikube/discover-api
https://github.com/k8guard/k8guard-start-from-here/tree/master/minikube/discover-cronjob
https://github.com/k8guard/k8guard-start-from-here/tree/master/minikube/report

and for cassandra-kafka-memached
https://github.com/k8guard/k8guard-start-from-here/tree/master/minikube/core


I will add it to our backlog to make a nice diagram explaining the deployment relations. it will hopefully be on the next version of the docs.


you can also take a look at the Makefile and see the exact Bash Command that makefile calls.

**Comment by iMartyn** [comment] 2017-07-26 18:24
Excellent!  Yeah, I think that this is just a documentation bug tbh.

Might I suggest renaming `minikube` folder to the more common and more encompassing `manifests`?

**Comment by medyagh** [comment] 2017-07-26 18:53
@iMartyn do you have example of any other project that they put their kuberentes yaml files in `manifests` folder? most of the projects out there put it in `minikube`, `kube` or `kuberentes` folder.  
the documentation doesn't have a bug, but it doesn't have example of deploying to prod. which can be very specific to each company.

**Comment by iMartyn** [comment] 2017-07-26 19:03
Kubernetes itself in kubeadm mode, and on CoreOS looks for `/etc/kubernetes/manifests` as a directory of manifests to deploy (it can be overridden with the kubelet `--pod-manifest-path` parameter).

In terms of it not being a documentation bug, you're providing a tool to monitor production kubernetes clusters without documenting how to deploy it (except hidden inside a makefile and only for dev).  To me, that's a documentation bug.  You've already said you'll add it to the backlog, I don't see why you wish to insist it's not a bug?

**Comment by medyagh** [comment] 2017-07-26 19:06
I would say it is a feature, bug is when there is an error with the current doc. the current doc is intended for minikube local testing. we do not have docs for deploying to prod, so that would be a feature for the docs not a bug.

**Comment by medyagh** [comment] 2017-07-26 19:07
could you please link to the yaml files in [kuberentes kubeadm repo](https://github.com/kubernetes/kubeadm) or any other k8s projects which been organized inside a `manifest` folder? if I see other k8s projects are going toward that convention, why not ! I would be willing to change the name.

**Comment by iMartyn** [comment] 2017-07-26 19:15
Not easily because kubeadm is a component of kubernetes.
I can point you to these examples of bugs, docs etc. showing that it does indeed do that : 
https://github.com/kubernetes/kubeadm/issues/106
https://coreos.com/kubernetes/docs/latest/deploy-master.html
https://github.com/kubernetes/kubernetes/issues/34307
https://github.com/kubernetes/kubernetes/issues/43967

**Comment by medyagh** [comment] 2017-07-26 19:16
ok thanks, thats actually a good suggestion, we could start calling the yaml files, manifests ! I am tired of calling them Yaml files anyways ! :)

**Comment by medyagh** [comment] 2017-07-26 19:19
@iMartyn btw please feel free to Make PRs for the github website and the docs, I would happily accept PRs.

**Comment by iMartyn** [comment] 2017-07-26 19:20
If we end up using it at work I almost certainly will :-)

**Comment by r0fls** [comment] 2017-08-15 00:13
Won't using cronjobs in 1.5 or 1.6 require starting the kube-apiserver with `--runtime-config=batch/v2alpha1=true` as per [here](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/)? That's probably worth documenting, for deploying to prod.

**Comment by milsonian** [comment] 2017-08-15 01:18
@r0fls Yes it does, good call out - I believe they are still alpha even in 1.7.

**Comment by milsonian** [comment] 2017-08-15 01:37
Also note there are pending PRs that provide a config flag so you can still run the discover API without alpha/cronjob (you would need to run the job via some other scheduling mechanism in that case):
https://github.com/k8guard/k8guardlibs/pull/16
https://github.com/k8guard/k8guard-discover/pull/19

...which should also be part of deployment documentation after it's merged so noting that here.

**Closed as completed** 2024-07-01 13:00 UTC
Labels: enhancement
